### ISSUE TITLE
Admin Image Upload button not working

### ISSUE THREAD

**Issue by Shristinaprajapati** [beater35/petsadoptify#1]
The upload button in the Admin dashboard is not functioning. 
![issue 1](https://github.com/beater35/petsadoptify/assets/119417721/7ee757e0-5c78-48a3-9b2e-fb4f81641731)

**Comment by Saugat3** [comment]
Sure i will fix that give me some time.

**Comment by Saugat3** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119481776/09b9d00d-9ea2-4097-a2fa-1926df2724ab)
![image](https://github.com/beater35/petsadoptify/assets/119481776/1e0d2376-216d-4674-a626-cebf45e3b4c3)

Now both the upload image and post button works please test and let me know.
