### ISSUE TITLE
Adopt me Redirection

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#12]
After clicking on adopt me button it should redirect to the listing page, not to the homepage.
![image](https://github.com/beater35/petsadoptify/assets/119406588/d27ed19c-2bfd-4c82-a924-b7bccf6faf0c)

**Comment by Saugat3** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119481776/095db65d-51b3-4557-b91f-f4a63a5e927f)

Now i have set the button links to listings.html, it will redirect to listings page.
