### ISSUE TITLE
form submission message error.

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#13]
After submission, there should be a successful submission message, but it shows the form again.
![image](https://github.com/beater35/petsadoptify/assets/119406588/804ef486-26de-49b5-9d20-108f2f25344f)

**Comment by Saugat3** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119481776/b4975cc6-9db9-472c-b92a-dc3864e730a4)
Now after the application is submitted, the form resets to become empty and the confirmation message for the submission is shown.
