### ISSUE TITLE
Additional Pets not showing.

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#14]
Additional Pets not showing.
![image](https://github.com/beater35/petsadoptify/assets/119406588/38106b4d-e42a-45e1-8b60-478504282d22)

**Comment by Saugat3** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119481776/0cfd3865-c57f-4a94-8dbd-e0bd51dddb4a)
The additional pets are showing now i have updated the javascript.
