### ISSUE TITLE
The pets are not being uploaded.

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#15]
The pets are not being uploaded and after uploading it should give a informative feedback.
![image](https://github.com/beater35/petsadoptify/assets/119406588/31986553-09f4-47fe-aba7-81537785efbb)

**Comment by beater35** [comment]
The bug is solved.

![image](https://github.com/beater35/petsadoptify/assets/92991325/0c64b844-abc5-4d17-8b18-2edbb4235b15)

![image](https://github.com/beater35/petsadoptify/assets/92991325/5ea1b7a7-19d6-4dd1-9400-4e88f401df7c)
