### ISSUE TITLE
align search and filter

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#16]
Please Align the search button and filtering option on same level.
![image](https://github.com/beater35/petsadoptify/assets/119406588/b9c45fd7-5bb2-4f7a-a433-265ee29ae71b)

**Comment by Saugat3** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119481776/a8f3765f-f1dc-492a-9520-7a0ed5c64ad0)
The bug is solved. The issue here was the search button CSS. The width of the search button was way more than required. The debugging is done and you can check on the server.
