### ISSUE TITLE
Chatbot's reply.

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#17]
Please fix the chatbot. It's not working.
![image](https://github.com/beater35/petsadoptify/assets/119406588/0453e19f-48ac-4692-adf3-1a0c4dd773b9)

**Comment by Shristinaprajapati** [comment]
![bugfixed](https://github.com/beater35/petsadoptify/assets/119417721/89758df6-c640-422b-815d-8a0e70ab9937)
Fixed
