### ISSUE TITLE
Inquiry Submission.

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#18]
Submission of an inquiry is working fine but the user should get an informative feedback  after the form has been submitted successfully.
![image](https://github.com/beater35/petsadoptify/assets/119406588/b3544981-e447-41a9-b746-eb1ce38820c0)

**Comment by Saugat3** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119481776/7d50f8d1-fe30-4d8f-9f5e-4ba60ccdde69)
![image](https://github.com/beater35/petsadoptify/assets/119481776/9f9b54ba-593c-4252-8c91-aa6a9e88b382)
The feedback and form refreshing functionality is added. Now the users can know when the form is submitted.
