### ISSUE TITLE
User Profile Button Absence During Pet Adoption Process

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#19]
After navigating to the listing page and attempting to initiate the pet adoption process, we've identified an issue wherein the user profile button fails to display. Instead, users are presented with the 'login' and 'signup' options.
![image](https://github.com/beater35/petsadoptify/assets/119406588/a5b89a27-f586-457a-886b-6d7d0c8ee4f9)

**Comment by Shristinaprajapati** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119417721/4caf6d47-ac91-4f31-be1c-bc19310906c1)
The user profile has been displayed in the adopt me redirect page.
