### ISSUE TITLE
SignUp

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#2]
The fonts are not looking good, fonts should be more visible/clear and bigger than this. And also fix the text highlighting.
![ISSUE](https://github.com/beater35/petsadoptify/assets/119406588/95be915b-f3e8-4e19-b7c2-6960e8e614c4)

**Comment by Saugat3** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119481776/74feae7e-36ea-4029-bb8c-b36f184f69b1)
![image](https://github.com/beater35/petsadoptify/assets/119481776/63d6ed73-a415-465d-9427-af776128064f)

I have increased the opacity to 80% now the font should look cleaner and more highlighted.
