### ISSUE TITLE
After Signup you are directed to old home page. Please correct it so that the Register button will pop a message saying registered successfully then. If the registration is successful it will direct to login page.

### ISSUE THREAD

**Issue by Shristinaprajapati** [beater35/petsadoptify#20]

**Comment by Shristinaprajapati** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119417721/c9db7857-6de5-427f-b0be-39fccf2ce5a6)

**Comment by beater35** [comment]
The bug is solved

![image](https://github.com/beater35/petsadoptify/assets/92991325/0ec74294-934a-4102-894e-acd9f007697e)

**Comment by beater35** [comment]
The bug is solved.

![image](https://github.com/beater35/petsadoptify/assets/92991325/47a1c2fc-fa42-47fe-a027-6b03039d8a96)
