### ISSUE TITLE
Edit the UI for the Search Filter

### ISSUE THREAD

**Issue by Shristinaprajapati** [beater35/petsadoptify#21]

**Comment by Shristinaprajapati** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119417721/0bf5f47d-c1cb-4831-ac88-95ba271536df)

**Comment by beater35** [comment]
The bug is solved.

![image](https://github.com/beater35/petsadoptify/assets/92991325/9007ded0-9d1f-40f4-b17e-4c387cec39f0)
