### ISSUE TITLE
Profile Setting

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#3]
after logging in when the user tries to go to his/her profile it shows John Doe who is not the user, it should show the actual user's name  instead.
![image](https://github.com/beater35/petsadoptify/assets/119406588/3e255001-2bf4-41c2-ad7b-8ac269d1484f)

**Comment by Shristinaprajapati** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119417721/9a643f3c-810f-482d-b760-da99cebca775)
The username has been displayed in the profile pop-up

**Comment by Shristinaprajapati** [comment]
The username has been displayed.
