### ISSUE TITLE
Email validation 

### ISSUE THREAD

**Issue by Shristinaprajapati** [beater35/petsadoptify#4]
Email validation in the signup is not completed as error emails are also being registered in the database.
![issue2](https://github.com/beater35/petsadoptify/assets/119417721/b6591aa8-201a-4e19-959b-63b2f7a4129c)

**Comment by beater35** [comment]
The bug is solved.

![image](https://github.com/beater35/petsadoptify/assets/92991325/5fa80655-dd21-45d5-9a70-b4decec045dc)
