### ISSUE TITLE
Confirmation Message

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#5]
In the contact us, when the user sends a message, a dialogue should open stating message has been sent successfully.
![image](https://github.com/beater35/petsadoptify/assets/119406588/499ba4c3-8a64-4e3a-ba5a-23617c358968)

**Comment by beater35** [comment]
The bug is solved.

![image](https://github.com/beater35/petsadoptify/assets/92991325/52d077b0-599f-414a-bdde-a122d8d714c5)
