### ISSUE TITLE
User profile setting after login

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#6]
after a user logs in and refreshes the page, it logs out automatically. Please fix this.
![image](https://github.com/beater35/petsadoptify/assets/119406588/22263e31-5880-4377-9265-6664f793f237)
![image](https://github.com/beater35/petsadoptify/assets/119406588/e0b8a888-4dce-4fd3-8169-3088e158bd72)

**Comment by beater35** [comment]
The bug is solved.

![image](https://github.com/beater35/petsadoptify/assets/92991325/df4b019f-bd16-4810-a17b-8ccc13eb2a8a)
