### ISSUE TITLE
Changing of Fonts

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#8]
The font changes after redirecting to another page.
![image](https://github.com/beater35/petsadoptify/assets/119406588/a434bcd9-0a9e-43ed-87b5-ddad57536849)
![image](https://github.com/beater35/petsadoptify/assets/119406588/ea1a2390-c135-4dfe-8e96-31db39602ce6)

**Comment by Saugat3** [comment]
![image](https://github.com/beater35/petsadoptify/assets/119481776/a6fc34e9-8734-42b1-9770-cbcbc8a949cb)
![image](https://github.com/beater35/petsadoptify/assets/119481776/41a5ede9-b0c2-42fe-8b77-528ca9e6d720)

now the font stays same in all the pages.
