### ISSUE TITLE
Register Issue

### ISSUE THREAD

**Issue by SabinB2000** [beater35/petsadoptify#9]
As a new user, when trying to register from a new email it says email is already in use. 
![image](https://github.com/beater35/petsadoptify/assets/119406588/47ae7bb7-1297-4199-abab-2256253a8009)

**Comment by beater35** [comment]
The bug is solved.

![image](https://github.com/beater35/petsadoptify/assets/92991325/235d5e8f-3673-432b-9c54-d69aa134e4ed)
